config/routes.rb
Rails.application.routes.draw do
  resources :principals
  root 'dashboard#show'

  get 'login' => 'authentications#new'
  post 'login' => 'authentications#create'
  delete 'logout' => 'authentications#destroy'

  get 'grades' => 'assignment_grades#index'

  get "/auth/:provider/callback" => "authentications#create"

  get 'student_achievements' => 'students#edit_achievements'
  get 'student_grades' => 'students#grades'

  resources :authentications
  resources :assignment_grades
  resources :students
  resources :parents
  resources :teachers
  resources :users
  resources :achievements

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    redirect_to login_path if !session[:person_type]

    @person = User.find(session[:user_id]) if session[:user_id]

    if session[:person_type] == "Student"
      @student = Student.find(User.find(session[:user_id]).person_id)
    elsif session[:person_type] == "Parent"
      @student = Parent.find(User.find(session[:user_id]).person_id).student
    end

  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/show.html.erb
<h1>Hay, <%= @person.name %></h1>
<p></p>


<% if session[:person_type] == "Teacher" %>
  <div class="cards">
    <%= link_to users_path do %>
      <div class="card">
        <div class="card-image">
        <%= image_tag("/users.png") %>
        </div>
        <div class="card-header">
          <h4><%= link_to "Manage Users", users_path %></h4>
        </div>
        <div class="card-copy">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, officiis sunt neque facilis culpa molestiae necessitatibus delectus veniam provident.</p>
        </div>
      </div>
    <% end %>

    <div class="card">
      <div class="card-image">
        <%= image_tag("/male-teacher-cartoon.jpg") %>
      </div>
      <div class="card-header">
        <h4><%= link_to "Manage Teachers", teachers_path %></h4>
      </div>
      <div class="card-copy">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, officiis sunt neque facilis culpa molestiae necessitatibus delectus veniam provident.</p>
      </div>
    </div>

    <div class="card">
      <div class="card-image">
        <%= image_tag("/students.jpg") %>
      </div>
      <div class="card-header">
        <h4><%= link_to "Manage Students", students_path %></h4>
      </div>
      <div class="card-copy">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
      </div>
    </div>

    <div class="card">
      <div class="card-image">
        <%= image_tag("/parents.jpg") %>
      </div>
      <div class="card-header">
        <h4><%= link_to "Manage Parents", parents_path %></h4>
      </div>
      <div class="card-copy">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, officiis sunt neque facilis culpa molestiae necessitatibus delectus veniam provident.</p>
      </div>
    </div>

    <div class="card">
      <div class="card-image">
        <%= image_tag("/grades.jpg") %>
      </div>
      <div class="card-header">
        <h4><%= link_to "Manage Grades", grades_path %></h4>
      </div>
      <div class="card-copy">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, officiis sunt neque facilis culpa molestiae necessitatibus delectus veniam provident.</p>
      </div>
    </div>
  </div>

<% elsif session[:person_type] == "Student" || session[:person_type] == "Parent" %>

  <div class="one-card">
    <div class="card">
      <div class="card-image">
        <%= image_tag("/grades.jpg") %>
      </div>
      <% if @student %>
      <div class="card-header">
        <h4><%= @student.first_name %> <%= @student.last_name %></h4>
      </div>
      <div class="card-copy">
        <p>GPA: <%= @student.average_grade %></p>
        <p>Class Rank: <%= @student.class_rank %></p>
        <p><%= link_to "View Grades", grades_path %></p>

  <% elsif %>
    <p>There are currently no students registered to your account.</p>
    <p>Please contact an administrator about adding your students.</p>
  <% end %>
</div>
</div>
</div>

<% elsif session[:person_type] == "Principal" %>

  <div class="one-card">
    <div class="card">
      <div class="card-image">
        <%= image_tag("/grades.jpg") %>
      </div>
      <div class="card-header">
        <h4><%= link_to "Click here for stats", principals_path %></h4>
      </div>
      <div class="card-copy">
        <h3>Total Number of Teachers: &nbsp <%= Principal.number_of_teachers %></h3>
        <h3>Total Number of Students:  &nbsp<%= Principal.number_of_students %></h3>
        <h3>Classroom Ratio:&nbsp
          <% if "#{Principal.number_of_teachers}" != 1 %>
            <% ratio = (Principal.number_of_students.to_f / Principal.number_of_teachers) %>
            <%= "#{Principal.number_of_teachers / Principal.number_of_teachers} : #{ratio.round(2)}" %>
          <% else %>
            <%= "#{Principal.number_of_teachers} : #{Principal.number_of_students}" %>
          <% end %>
        </h3>
        <h3>Number of Assignments Completed: &nbsp <%= "#{Principal.completed_assignments}" %> </h3>
      </div>
    </div>
  </div>


<% elsif session[:user_id] %>
  <%= link_to "View Grades", grades_path %><br>
<% end %>