config/routes.rb
Rails.application.routes.draw do
  resources :principals
  root 'dashboard#show'

  get 'login' => 'authentications#new'
  post 'login' => 'authentications#create'
  delete 'logout' => 'authentications#destroy'

  get 'grades' => 'assignment_grades#index'

  get "/auth/:provider/callback" => "authentications#create"

  get 'student_achievements' => 'students#edit_achievements'
  get 'student_grades' => 'students#grades'

  resources :authentications
  resources :assignment_grades
  resources :students
  resources :parents
  resources :teachers
  resources :users
  resources :achievements

end

app/models/student.rb
require 'constants.rb'

class Student < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :principal
  has_many :parents
  has_many :assignment_grades, dependent: :destroy
  has_many :users, as: :person
  has_many :student_achievements, dependent: :destroy
  has_many :achievements, through: :student_achievements
  accepts_nested_attributes_for :achievements, allow_destroy: true
  accepts_nested_attributes_for :assignment_grades,
      reject_if: :all_blank,
      allow_destroy: true
  validates :first_name, presence: true
    #
  def average_grade
    assignment_grades.average(:grade) || 0
  end

  def class_rank
    students = Student.all
    better_students = students.select {|s| (s.average_grade || 0) > (self.average_grade || 0)}
    rank = better_students.count + 1
  end

  include Constants

  def total_achievements
    achievements.sum(:points)
  end

  def achievement_grade
    Constants::THRESHOLDS.each do |k,v|
      if total_achievements >= v
        return k
      end
    end
    return :F
  end

  def self.for_select(person_id, person_type)
    if person_type == "Student"
      s = Student.joins("LEFT JOIN 'users' ON students.id = users.person_id and users.person_type = 'Student'").where("users.id IS NULL OR students.id = #{person_id}")
    else
      s = Student.joins("LEFT JOIN 'users' ON students.id = users.person_id and users.person_type = 'Student'").where("users.id IS NULL")
    end
    s.collect {|temp| [temp.first_name, temp.to_global_id]}
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :grades, :destroy]
  before_action :authenticate_principal_or_teacher

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  def grades
    if @student.assignment_grades.count > 0
      @assignment_grades = @student.assignment_grades.all
    end
  end
  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    @assignment_grades = @student.assignment_grades.all
    @achievements_list = Achievement.all
    @student = Student.find(params[:id])
    @student.assignment_grades.build
    @student.student_achievements.build
  end

  def edit_achievements
    @student = Student.find(params[:id])
    @achievements_list = Achievement.all
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    unless @student.save
      render :new
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update

    if params[:achievements]
      achievements = params[:achievements]
        achievements.each do |a|
          new_achievement = Achievement.find(a[0].to_i)
          if a[1] == "1" && !@student.achievements.pluck(:name).include?(new_achievement.name)
            @student.achievements << new_achievement
          elsif a[1] == "0" && @student.achievements.pluck(:name).include?(new_achievement.name)
            @student.achievements.delete(new_achievement)
          end
      end
    end

    unless @student.update(student_params)
      format.html { render :edit }
    end
    @students = Student.all
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy

    @students = Student.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :teacher_id, assignment_grades_attributes: [:id, :grade, :assignment_name, :assignment_date, :student_id, :_destroy])
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_assignment_grades_conditional.html.erb
<% if assignment_grades %>
  <table class= "tables">
    <thead>
      <tr>
        <th>Grade  </th>
        <th>Assignment name </th>
        <th>Assignment date </th>
        <th>Student </th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody class="grades_table">
        <%= render assignment_grades %>
    </tbody>
  </table>
  <br>

  <%= link_to 'New Assignment grade', new_assignment_grade_path(student: @student), class: "add-user-button add-new", remote: true if session[:person_type] == "Teacher"%>

<% else %>

  <p>Sorry. There are no assignments for this user. Either your teacher needs to create some, or your permissions need to be changed. Contact your teacher for more details.</p>

  <%= link_to 'New Assignment grade', new_assignment_grade_path(student: @student), class: "add-user-button add-new", remote: true if session[:person_type] == "Teacher"%>
<% end %>

app/views/students/_assignment_grades_table.html.erb
<h2>Grades</h2>

<% if session[:person_type] == "Parent" %>
  <%= form_for @parent do |f| %>
    <%= f.label "Would you like to receive weekly emails?" %>
    <%= f.check_box :email_preferences %>
    <%= f.submit %>
  <% end %>
<% end %>

<div class="assignment-grades-conditional">
  <%= render partial: 'assignment_grades_conditional', locals: {assignment_grades: @assignment_grades} %>
</div>

app/views/students/_form.html.erb
<link href='http://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
<div id="form-main">
  <div id="form-div">
    <div class="form" id="form1">
    <%= form_for(@student, remote: true) do |f| %>
      <% if @student.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

          <ul>
          <% @student.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <p class="name">
        <%= f.text_field :first_name,  class: "feedback-input", placeholder: "First Name" %>
      </p>
      <p class="name">


        <%= f.text_field :last_name,  class: "feedback-input", placeholder: "Last Name" %>
      </p>
      <p class="name">
        <%= f.label :teacher %><br>
        <%= f.collection_select :teacher_id, Teacher.all, :id, :first_name, :prompt => "Select Teacher..." %>

      </p>
      <p class="submit">
        <%= f.submit "Update Student", :id => "button-blue"%>
      </p>

    <% end %>
  </div>
</div>

app/views/students/_student.html.erb
<tr>
  <td><%= student.first_name %></td>
  <td><%= student.last_name %></td>
  <td><%= "#{student.teacher.first_name} #{student.teacher.last_name}" if student.teacher %></td>
  <td><%= button_to 'Show', student, :method => :get  %></td>
  <td><%= button_to 'Edit', edit_student_path(student), :method => :get, remote: true %></td>
  <td><%= button_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }, remote: true  %></td>
  <td><%= button_to 'Manage assignments', student_grades_path(id: student.id), :method => :get, remote: true %></td>
  <td><%= button_to "Manage achievements", student_achievements_path(id: student.id), :method => :get, remote: true %></td>
</tr>

app/views/students/_students_table.html.erb
<thead>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Teacher</th>
    <th colspan="8"></th>
  </tr>
</thead>
<tbody class="students_table">
  <%= render students %>
</tbody>

app/views/students/destroy.js.erb
$(".manage_achievements").html("");
$(".add_assignment").html("");
$(".new_student").html("");
$(".manage_assignments").html("");
$(".students").html("<%= j(render partial: "students_table", locals: {students: @students}) %>");
$(".manage_assignments").html("");

app/views/students/edit.js.erb
$(".manage_assignments").html("");
$(".manage_achievements").html("");
$(".new_student").html("<%= j(render 'form') %>");

app/views/students/edit_achievements.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <h5>Achievements - Total Points: <%=@student.total_achievements%></h5>
  <% student_list = @student.achievements.pluck(:name) %>

  <% @achievements_list.each do |a| %>

    <div class="field">
      <%= label_tag a.name %> (<%= a.points %>)
      <% if student_list.include?(a.name) %>
        <%= check_box :achievements, a.id, {checked: true}  %>
      <% else %>
        <%= check_box :achievements, a.id, {checked: false}  %>
      <% end %>
    </div>

  <% end %>

  <div class="field">
    <%= f.hidden_field :id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit_achievements.js.erb
$(".manage_assignments").html("");
$(".add_assignment").html("");
$(".new_student").html("");
$(".manage_achievements").html("<%= j(render 'edit_achievements') %>");

app/views/students/grades.js.erb
$(".manage_achievements").html("");
$(".add_assignment").html("");
$(".new_student").html("");
$(".manage_assignments").html("<%= j(render 'index') %>");

app/views/students/index.html.erb
<link href='http://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>

<h1 class="table-name">Students</h1>

<table class="students tables">
  <%= render partial: "students_table", locals: {students: @students} %>
</table>
<br>

<div class="add-new"><%= link_to 'New Student', new_student_path, :class => "add-user-button", remote: true %></div>

<div class="new_student">
</div>
<div class="manage_assignments">
</div>
<div class="add_assignment">
</div>
<div class="manage_achievements">
</div>

app/views/students/new.js.erb
$(".new_student").html("<%= j(render 'form') %>");

app/views/students/show.html.erb
<div id="form-main">
  <div id="form-div">
    <div class="form" id="form1">
        <strong>Student's Name:</strong>
        <%= "#{@student.first_name} #{@student.last_name}" %>
        <br>
        <strong>Student's Parent(s):</strong>
        <% if @student.parents.first == nil %>
          <p> No parent listed in the database. </p>
        <% else %>
          <%= "#{@student.parents.first.first_name} #{@student.parents.first.last_name}" %>
        <% end %>
        <br>
        <br>
        <strong>Student's Grades:</strong>
        <table>
          <thead>
            <tr>
              <th>Grade</th>
              <th>Assignment</th>
              <th>Date</th>
            </tr>
          </thead>
          <table>
            <tbody>
              <% @student.assignment_grades.each do |assignment_grade| %>
                <tr>
                  <td><%= assignment_grade.grade %></td>
                  <td><%= assignment_grade.assignment_name %></td>
                  <td><%= assignment_grade.assignment_date %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <br>
          <p>
            <strong>Student's Achievements:</strong>
            <p>
               <%= "Total points: #{@student.total_achievements} | Grade equivalent: #{@student.achievement_grade}"%>
            </p>
          </p>
      <%= link_to 'Back', students_path %>
    </div>
  </div>
</div>

app/views/students/update.js.erb
$(".students").html("<%= j(render partial: "students_table", locals: {students: @students}) %>");
$(".new_student").html("");
$(".manage_achievements").html("");