config/routes.rb
Rails.application.routes.draw do
  resources :principals
  root 'dashboard#show'

  get 'login' => 'authentications#new'
  post 'login' => 'authentications#create'
  delete 'logout' => 'authentications#destroy'

  get 'grades' => 'assignment_grades#index'

  get "/auth/:provider/callback" => "authentications#create"

  get 'student_achievements' => 'students#edit_achievements'
  get 'student_grades' => 'students#grades'

  resources :authentications
  resources :assignment_grades
  resources :students
  resources :parents
  resources :teachers
  resources :users
  resources :achievements

end

app/models/principal.rb
class Principal < ActiveRecord::Base
  has_many :parents, through: :students
  has_many :users, as: :person
  has_many :students

  def self.number_of_teachers
    @teachers = Teacher.all
    @teachers.count
  end

  def self.number_of_students
    @students = Student.all
    @students.count
  end

  def self.completed_assignments
   @assignment_grade = AssignmentGrade.all
   @assignment_grade.count
  end

  def self.display_assignment_name(student)
    @assignment_grade = AssignmentGrade.all
    @assignment_grade.each do |g|
      AssignmentGrade.find_by(student_id: student.id).assignment_name
    end
  end

  def self.display_student_grades(student)
    AssignmentGrade.find_by(student_id: student.id).grade
  end

  def self.display_parent_first(student)
    Parent.find_by(student_id: student.id).first_name
  end

  def self.display_parent_last(student)
    Parent.find_by(student_id: student.id).last_name
  end

end

app/controllers/principals_controller.rb
class PrincipalsController < ApplicationController
  before_action :set_principal, only: [:show]
  before_action :authenticate_principal

  def index
    @principals = Principal.all
    @teachers = Teacher.all
    @students = Student.all
    @parents = Parent.all
    @assignment_grades = AssignmentGrade.all
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_principal
      @principal = Principal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def principal_params
      params.require(:principal).permit(:email, :first_name, :last_name)
    end
end

app/helpers/principals_helper.rb
module PrincipalsHelper
end

app/views/principals/_form.html.erb
<%= form_for(@principal) do |f| %>
  <% if @principal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@principal.errors.count, "error") %> prohibited this principal from being saved:</h2>

      <ul>
      <% @principal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/principals/edit.html.erb
<h1>Editing Principal</h1>

<%= render 'form' %>

<%= link_to 'Show', @principal %> |
<%= link_to 'Back', principals_path %>

app/views/principals/index.html.erb
<p id="notice"><%= notice %></p>

<link href='http://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
<div id="title-container-single"
  <div class="Three-Dee-Container-single">
    <h1 class="Three-Dee">Staff List</h1>
  </div>
</div>


  <div class="cards2">
    <% @teachers.each do |t| %>
      <div class="card">
        <div class="card-image">
        <%= image_tag("/users.png") %>
        </div>
        <div class="card-header">
          <h3><%= t.first_name %> <%=  t.last_name %></h3>
        </div>
        <div class="card-copy">
          <% @students.where("teacher_id = ?", t.id).each do |s| %>
            <%= link_to "#{s.first_name} #{s.last_name}", student_path(s) %> <br>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

app/views/principals/new.html.erb
<h1>New Principal</h1>

<%= render 'form' %>

<%= link_to 'Back', principals_path %>

app/views/principals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @principal.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @principal.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @principal.last_name %>
</p>

<%= link_to 'Edit', edit_principal_path(@principal) %> |
<%= link_to 'Back', principals_path %>