config/routes.rb
Rails.application.routes.draw do
  resources :principals
  root 'dashboard#show'

  get 'login' => 'authentications#new'
  post 'login' => 'authentications#create'
  delete 'logout' => 'authentications#destroy'

  get 'grades' => 'assignment_grades#index'

  get "/auth/:provider/callback" => "authentications#create"

  get 'student_achievements' => 'students#edit_achievements'
  get 'student_grades' => 'students#grades'

  resources :authentications
  resources :assignment_grades
  resources :students
  resources :parents
  resources :teachers
  resources :users
  resources :achievements

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :students
  has_many :users, as: :person
  validates :first_name, presence: true

  def self.for_select(person_id, person_type)
    if person_type == "Teacher"
      t = Teacher.joins("LEFT JOIN 'users' ON teachers.id = users.person_id and users.person_type = 'Teacher'").where("users.id IS NULL OR users.id = #{person_id}")
    else
      t = Teacher.joins("LEFT JOIN 'users' ON teachers.id = users.person_id and users.person_type = 'Teacher'").where("users.id IS NULL")
    end
    t.collect {|temp| [temp.first_name, temp.to_global_id]}
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_teacher 

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:first_name, :last_name)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<link href='http://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
<div id="form-main">
  <div id="form-div">
    <div class="form" id="form1">
    <%= form_for(@teacher) do |f| %>
      <% if @teacher.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>
          <ul>
          <% @teacher.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <p class="name">
        <%= f.text_field :first_name, placeholder: "First Name", class: "validate[required,custom[onlyLetter],length[0,100]] feedback-input" %>
      </p>
      <p class="email">
        <%= f.text_field :last_name,  placeholder: "Last Name", :class => "validate[required,custom[email]] feedback-input" %>
      </p>
      <p class="submit">
        <%= f.submit "Add Teacher", :id => "button-blue" %>
      </p>
    <% end %>
    </div>


    <div class="git-link" >
      <%= link_to 'Back', teachers_path %>
    </div>

  </div>






</div>

app/views/teachers/edit.html.erb
<link href='http://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
<div class="Three-Dee-Container">
  <h1 class="Three-Dee">Edit Teacher</h1>
</div>

<%= render 'form' %>

app/views/teachers/index.html.erb
<link href='http://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>

<h1 class="table-name">Teachers</h1>


<table class="tables">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.first_name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= button_to 'Show', teacher, :method => :get %></td>
        <td><%= button_to 'Edit', edit_teacher_path(teacher), :method => :get %></td>
        <td><%= button_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="add-new"><%= link_to 'New Teacher', new_teacher_path, :class => "add-user-button" %></div>

  <!-- <div class="vertical-tabs-container">
    <div class="vertical-tabs">
      <% @teachers.each_with_index do |teacher, i| %>
        <a href="javascript:void(0)" class="js-vertical-tab vertical-tab is-active" rel="tab<%=i%>"><%= teacher.first_name %><%= teacher.last_name %> </a>
      <% end %>
    </div>

    <div class="vertical-tab-content-container">
      <% @teachers.each_with_index do |teacher, i| %>
        <a href="" class="js-vertical-tab-accordion-heading vertical-tab-accordion-heading is-active" rel="tab<%=i%>">Item 1</a>
        <div id ="tab<%=i%>" class="js-vertical-tab-content vertical-tab-content">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt pellentesque lorem, id suscipit dolor rutrum id. Morbi facilisis porta volutpat. Fusce adipiscing, mauris quis congue tincidunt, sapien purus suscipit odio, quis dictum odio tortor in sem. Ut sit amet libero nec orci mattis fringilla. Praesent eu ipsum in sapien tincidunt molestie sed ut magna. Nam accumsan dui at orci rhoncus pharetra tincidunt elit ullamcorper. Sed ac mauris ipsum. Nullam imperdiet sapien id purus pretium id aliquam mi ullamcorper.
          <%= link_to 'Show', teacher %>
          <%= link_to 'Edit', edit_teacher_path(teacher) %>
          <%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        </div>
      <% end %>
    </div>
  </div>
  <%= link_to 'New Teacher', new_teacher_path %> -->


  <!-- <div class="vertical-tabs-container">
    <div class="vertical-tabs">
      <a href="javascript:void(0)" class="js-vertical-tab vertical-tab is-active" rel="tab1">Item 1</a>
      <a href="javascript:void(0)" class="js-vertical-tab vertical-tab" rel="tab2">Item 2</a>
      <a href="javascript:void(0)" class="js-vertical-tab vertical-tab" rel="tab3">Item 3</a>
      <a href="javascript:void(0)" class="js-vertical-tab vertical-tab" rel="tab4">Item 4</a>
    </div>

    <div class="vertical-tab-content-container">
      <a href="" class="js-vertical-tab-accordion-heading vertical-tab-accordion-heading is-active" rel="tab1">Item 1</a>
      <div id="tab1" class="js-vertical-tab-content vertical-tab-content">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt pellentesque lorem, id suscipit dolor rutrum id. Morbi facilisis porta volutpat. Fusce adipiscing, mauris quis congue tincidunt, sapien purus suscipit odio, quis dictum odio tortor in sem. Ut sit amet libero nec orci mattis fringilla. Praesent eu ipsum in sapien tincidunt molestie sed ut magna. Nam accumsan dui at orci rhoncus pharetra tincidunt elit ullamcorper. Sed ac mauris ipsum. Nullam imperdiet sapien id purus pretium id aliquam mi ullamcorper.</p>
      </div>

      <a href="" class="js-vertical-tab-accordion-heading vertical-tab-accordion-heading" rel="tab2">Item 2</a>
      <div id="tab2" class="js-vertical-tab-content vertical-tab-content">
        <p>Ut laoreet augue et neque pretium non sagittis nibh pulvinar. Etiam ornare tincidunt orci quis ultrices. Pellentesque ac sapien ac purus gravida ullamcorper. Duis rhoncus sodales lacus, vitae adipiscing tellus pharetra sed. Praesent bibendum.</p>
      </div>

      <a href="" class="js-vertical-tab-accordion-heading vertical-tab-accordion-heading" rel="tab3">Item 3</a>
      <div id="tab3" class="js-vertical-tab-content vertical-tab-content">
        <p>Donec mattis mauris gravida metus laoreet non rutrum sem viverra. Aenean nibh libero, viverra vel vestibulum in, porttitor ut sapien. Phasellus tempor lorem id justo ornare tincidunt. Nulla faucibus, purus eu placerat fermentum, velit mi iaculis nunc, bibendum tincidunt ipsum justo eu mauris. Nulla facilisi. Vestibulum vel lectus ac purus tempus suscipit nec sit amet eros. Nullam fringilla, enim eu lobortis dapibus, quam magna tincidunt nibh, sit amet imperdiet dolor justo congue turpis.</p>
      </div>

      <a href="" class="js-vertical-tab-accordion-heading vertical-tab-accordion-heading" rel="tab4">Item 4</a>
      <div id="tab4" class="js-vertical-tab-content vertical-tab-content">
        <p>Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus dui urna, mollis vel suscipit in, pharetra at ligula. Pellentesque a est vel est fermentum pellentesque sed sit amet dolor. Nunc in dapibus nibh. Aliquam erat volutpat. Phasellus vel dui sed nibh iaculis convallis id sit amet urna. Proin nec tellus quis justo consequat accumsan. Vivamus turpis enim, auctor eget placerat eget, aliquam ut sapien.</p>
      </div>
    </div>
  </div> -->

app/views/teachers/new.html.erb
<link href='http://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
<div class="Three-Dee-Container">
  <h1 class="Three-Dee">New Teacher</h1>
</div>

<%= render 'form' %>

app/views/teachers/show.html.erb
<div id="form-main">
  <div id="form-div">
    <div class="form" id="form1">




      <p>
        <strong>Teacher First Name:</strong>
        <%= @teacher.first_name %>
      </p>
      <p>
        <strong>Teacher Last Name:</strong>
        <%= @teacher.last_name %>
      </p>

      <%= link_to 'Edit', edit_teacher_path(@teacher) %> |
      <%= link_to 'Back', teachers_path %>
    </div>
  </div>
</div>